src/Entity/Personne.php
<?php

namespace App\Entity;
use Symfony\Component\Validator\Constraints as Assert;

use Doctrine\ORM\Mapping as ORM;

/**
 * Personne
 *
 * @ORM\Table(name="personne")
 * @ORM\Entity
 */
class Personne
{
    /**
     * @var int
     *
     * @ORM\Column(name="idpersonne", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $idpersonne;

    /**
     * @var string|null
     * @Assert\NotBlank
     * @ORM\Column(name="nom", type="string", length=45, nullable=true)
     */
    private $nom;

    /**
     * @var string|null
     * @Assert\NotBlank
     * @ORM\Column(name="prenom", type="string", length=45, nullable=true)
     */
    private $prenom;

    /**
     * @var \DateTime|null
     * @Assert\LessThan("now", message="Date  invalide")
     * @Assert\NotBlank
     * @ORM\Column(name="datedenaissance", type="date", nullable=true)
     */
    private $datedenaissance;

    /**
     * @var string|null
     * @Assert\NotBlank
     * @Assert\Regex(
     *     pattern="/^(?:(?:\+|00)33|0)\s*[1-9](?:[\s.-]*\d{2}){4}$/",
     *     match=true,
     *     message="Le n° de téléphone doit être valide"
     * )
     * @ORM\Column(name="telephone", type="string", length=45, nullable=true)
     */
    private $telephone;

    /**
     * @var string|null
     * @Assert\NotBlank
     * @Assert\Email(
     *  message = "La valeur entrée dans le champs email est invalide"
     * )
     *
     * @ORM\Column(name="email", type="string", length=45, nullable=true)
     */
    private $email;

    /**
     * Get Age
     * 
     */
    public function getAge(){

    	$dateInterval = $this->datedenaissance->diff(new \DateTime());
    	return $dateInterval->y;

	}

    /**
     * Get the value of email
     *
     * @return  string|null
     */ 
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Set the value of email
     *
     * @param  string|null  $email
     *
     * @return  self
     */ 
    public function setEmail($email)
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Get the value of telephone
     *
     * @return  string|null
     */ 
    public function getTelephone()
    {
        return $this->telephone;
    }

    /**
     * Set the value of telephone
     *
     * @param  string|null  $telephone
     *
     * @return  self
     */ 
    public function setTelephone($telephone)
    {
        $this->telephone = $telephone;

        return $this;
    }

    /**
     * Get the value of datedenaissance
     *
     * @return  \DateTime|null
     */ 
    public function getDatedenaissance()
    {
        return $this->datedenaissance;
    }

    /**
     * Set the value of datedenaissance
     *
     * @param  \DateTime|null  $datedenaissance
     *
     * @return  self
     */ 
    public function setDatedenaissance($datedenaissance)
    {
        $this->datedenaissance = $datedenaissance;

        return $this;
    }

    /**
     * Get the value of prenom
     *
     * @return  string|null
     */ 
    public function getPrenom()
    {
        return $this->prenom;
    }

    /**
     * Set the value of prenom
     *
     * @param  string|null  $prenom
     *
     * @return  self
     */ 
    public function setPrenom($prenom)
    {
        $this->prenom = $prenom;

        return $this;
    }

    /**
     * Get the value of idpersonne
     *
     * @return  int
     */ 
    public function getIdpersonne()
    {
        return $this->idpersonne;
    }

    /**
     * Get the value of nom
     *
     * @return  string|null
     */ 
    public function getNom()
    {
        return $this->nom;
    }

    /**
     * Set the value of nom
     *
     * @param  string|null  $nom
     *
     * @return  self
     */ 
    public function setNom($nom)
    {
        $this->nom = $nom;

        return $this;
    }
}

src/Form/PersonneType.php
<?php

namespace App\Form;

use App\Entity\Personne;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TelType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\BirthdayType;

class PersonneType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom', TextType::class, [
                'attr'=> [
                    'class' => 'form-control'
                ],
                'label' => "Votre nom",
                'required' => true,
                'constraints' => [
                    new NotBlank([
                        'message' => "Saisir votre Prénom."
                    ])
                ],
            ]
        )
            ->add('prenom', TextType::class, [
                'attr'=> [
                    'class' => 'form-control'
                ],
                'label' => "Votre prénom",
                'required' => true,
                'constraints' => [
                    new NotBlank([
                        'message' => "Saisir votre Prénom."
                    ])
                ],
            ])
            ->add('datedenaissance', BirthdayType::class, [
                'attr'=> [
                    'class' => 'form-control',
                ],
                'widget' => 'single_text',
                'label' => "Votre date de naisssance",
                'required' => true,
                'constraints' => [
                    new NotBlank([
                        'message' => "Saisir votre date de naissance."
                    ])
                ],
            ])
            ->add('telephone', TelType::class, [
                'attr'=> [
                    'class' => 'form-control'
                ],
                'label' => "Votre numéro de téléphone",
                'required' => true,
                'constraints' => [
                    new NotBlank([
                        'message' => "Saisir votre numéro de téléphone."
                    ])
                ],
            ])
            ->add('email', EmailType::class, [
                'attr'=> [
                    'class' => 'form-control'
                ],
                'label' => "Votre Email",
                'required' => true,
                'constraints' => [
                    new NotBlank([
                        'message' => "Saisir votre email"
                    ])
                ],
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Personne::class,
        ]);
    }
}

src/Controller/PersonneController.php
<?php

namespace App\Controller;

use App\Entity\Personne;
use App\Form\PersonneType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/")
 */
class PersonneController extends AbstractController
{
    /**
     * @Route("/", name="personne_index", methods={"GET"})
     */
    public function index(): Response
    {
        $personnes = $this->getDoctrine()
            ->getRepository(Personne::class)
            ->findAll();

        return $this->render('personne/index.html.twig', [
            'personnes' => $personnes,
        ]);
    }

    /**
     * @Route("/new", name="personne_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $personne = new Personne();
        $form = $this->createForm(PersonneType::class, $personne);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($personne);
            $entityManager->flush();

            return $this->redirectToRoute('personne_index');
        }

        return $this->render('personne/new.html.twig', [
            'personne' => $personne,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{idpersonne}", name="personne_show", methods={"GET"})
     */
    public function show(Personne $personne): Response
    {
        return $this->render('personne/show.html.twig', [
            'personne' => $personne,
        ]);
    }

    /**
     * @Route("/{idpersonne}/edit", name="personne_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Personne $personne): Response
    {
        $form = $this->createForm(PersonneType::class, $personne);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('personne_index');
        }

        return $this->render('personne/edit.html.twig', [
            'personne' => $personne,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{idpersonne}", name="personne_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Personne $personne): Response
    {
        if ($this->isCsrfTokenValid('delete'.$personne->getIdpersonne(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($personne);
            $entityManager->flush();
        }

        return $this->redirectToRoute('personne_index');
    }
}

templates/personne/_delete_form.html.twig
<form method="post" action="{{ path('personne_delete', {'idpersonne': personne.idpersonne}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ personne.idpersonne) }}">
    <button class="btn btn-danger float-right mr-1">Effacer</button>
</form>

templates/personne/_form.html.twig
{{ form_start(form) }}
    <div class="form-group">
    {{ form_widget(form) }}
    </div>
    <button class="btn btn-primary float-right">{{ button_label|default('Sauvegarder') }}</button>
{{ form_end(form) }}

templates/personne/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Édition d'un utilisateur{% endblock %}

{% block body %}
<div class="container mt-4">
    <h1 class="text-center">Édition d'un utilisateur</h1>
    {{ include('personne/_form.html.twig', {'button_label': 'Valider'}) }}

    {{ include('personne/_delete_form.html.twig') }}

     <a class="btn btn-primary float-left mb-2" href="{{ path('personne_index') }}">Revenir à la liste</a>
</div>
{% endblock %}

templates/personne/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des utilisateurs{% endblock %}

{% block body %}
<div class="container">
    <h1 class="text-center mt-4">Liste des utilisateurs</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Nom</th>
                <th>Prénom</th>
                <th>Date de naissance</th>
                <th>Téléphone</th>
                <th>E-mail</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for personne in personnes %}
            <tr>
                <td>{{ personne.nom }}</td>
                <td>{{ personne.prenom }}</td>
                <td>{{ personne.datedenaissance ? personne.datedenaissance|date('Y-m-d') : '' }}</td>
                <td>{{ personne.telephone }}</td>
                <td>{{ personne.email }}</td>
                <td>
                    <a href="{{ path('personne_show', {'idpersonne': personne.idpersonne}) }}">Voir</a>
                    <a href="{{ path('personne_edit', {'idpersonne': personne.idpersonne}) }}">Éditer</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">Aucun enregistrement trouvé</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a class="btn btn-primary float-right" href="{{ path('personne_new') }}">Créer un nouvel utilisateur</a>
</div>
{% endblock %}

templates/personne/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Personne{% endblock %}

{% block body %}
<div class="container">
    <h1 class="text-center">Créer un nouvel utilisateur </h1>

    {{ include('personne/_form.html.twig') }}

    <a class="btn btn-primary"href="{{ path('personne_index') }}">Retour à la liste</a>
</div>

{% endblock %}

templates/personne/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Personne{% endblock %}

{% block body %}
<div class="container">
    <h1 class="my-5">{{ personne.nom }} {{ personne.prenom }}</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Age</th>
                <td>{{ personne.age }} ans</td>
            </tr>
            <tr>
                <th>Téléphone</th>
                <td>{{ personne.telephone }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ personne.email }}</td>
            </tr>
        </tbody>
    </table>

    <a class="btn btn-primary" href="{{ path('personne_index') }}">Revenir à la liste</a>

    <a class="btn btn-primary" href="{{ path('personne_edit', {'idpersonne': personne.idpersonne}) }}">Éditer</a>

    {{ include('personne/_delete_form.html.twig') }}
</div>
{% endblock %}